#!/bin/bash
set -e

cp -r test rapidfuzz_reference "$AUTOPKGTEST_TMP"
cp debian/tests/CMakeLists.txt "$AUTOPKGTEST_TMP"/test
mkdir "$AUTOPKGTEST_TMP"/build
cd "$AUTOPKGTEST_TMP"/build
CXX=g++ cmake ../test
make
make test || make test ARGS="--rerun-failed --output-on-fail"
